name: Node.js CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: "212.227.155.91"
        username: "root"
        password: "!2Zc727cI1"
        port: 22
        script: |
          cd ~/apps/fallback
          git reset --hard HEAD
          git clean -f -d
          git pull origin main
          git status
          pnpm install
          pnpm build
